test_that("fit_all_models has no mislabeled doubly robust model", {
  d <- simulate_test_cohort()
  ps <- build_ps_model(d, "exposure", c("age", "diabetes", "hypertension"))
  m <- match_cohort(ps)
  bin <- fit_all_models(ps, m$data, "outcome", type = "binary")
  cont <- fit_all_models(ps, m$data, "outcome", type = "continuous")
  expect_false(any(grepl("Doubly robust", names(bin$models))))
  expect_false(any(grepl("Doubly robust", names(cont$models))))
  expect_equal(length(bin$models), 3)
  expect_equal(length(cont$models), 3)
})
